name: Build + Deploy

on: 
  release:
    types: [prereleased,released]

defaults:
  run:
    shell: pwsh
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    name: 资源构建
    steps:
     - uses: actions/checkout@v3
       with:
          submodules: 'recursive'

     - name: 安装.NET
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: '6.0.100'
        
     - name: 构建
       run: |
          cd ClassLibrary1
          dotnet publish -r win-x64 -f net6.0 -c Release --self-contained false

     - name: 打包
       run: |
          Compress-Archive -Path ./ClassLibrary1/bin/Release/net6.0/win-x64/publish/击打提示怪物血量.dll,说明.txt Release-win-x64.zip
          
     
     
     - uses: IsaacShelton/update-existing-release@v1.3.2
       with:
         token: ${{secrets.GITHUB_TOKEN}}
         release: ${{ github.ref }}
         tag: ${{ github.ref_type }}
         replace: true
         files: >
           Release-win-x64.zip
      
     


